### ISSUE TITLE
add CNAME for gh-pages hosting

### ISSUE THREAD

**Issue by ryanpitts** [mozilla/mozfest-schedule-app#1]
For SRCCON, we set up a schedule.srccon.org subdomain and let gh-pages host the schedule app. Just need a CNAME [like this one](https://github.com/OpenNews/srccon-schedule/blob/gh-pages/CNAME) to make it work.

This approach means no deployment required -- when you update sessions.json with any changes, everyone's schedule is updated on next reload.

**Comment by mmmavis** [comment]
Thanks for filing this ticket, @ryanpitts! :tada: 

@jbuck, does this require any devops work? I guess we need to decide on the url first... correct?

/cc @hannahkane

**Comment by mmmavis** [comment]
@ryanpitts 

Could you tell me more about how your Python script works? :grin:  Does it fetch data from Google Spreadsheet periodically, turn it into `.json` file, and magically push that file to the github repo?

**Comment by ryanpitts** [comment]
Here's the script right here: https://github.com/ryanpitts/membot/blob/master/membot/apps/membot/commands/update_mozfest_schedule.py

You can see the vars at the top that would need to be modified to point it at the proper repo and give it the right Google creds and spreadsheet key. Once you've got those set up, you just need to run `update_srccon_schedule()` (or whatever you rename it to), and the script:

* pulls data from the spreadsheet you point it at
* converts everything into a JSON array, where each row becomes an object with keys matching the spreadsheet's column names (so we'll want to make sure column names are valid JSON keys)
* optionally stores a local copy of the JSON (for testing, probably best to turn this off)
* pushes a commit with a new `sessions.json` to the GitHub repo you point it at

You could absolutely put this script on a cron if you want, although then it's firing off even if there have been no changes. For our use, I hooked it up to a chatbot command so we could trigger the script every time we knew there was a change.

**Comment by ryanpitts** [comment]
Oh, this also assumes that you're storing GitHub and Google auth tokes as env variables.

If there's a repo already for the mozfest schedule app, I'd be happy to set up a version of the script that has all the right GitHub and Google settings and get it tested and working locally. We'd just need to decide where the script should live.

**Comment by mmmavis** [comment]
Wow! Lovely! I couldn't get Google API auth to work when I tried to use a npm module few days ago.  And now your Python script is here to rescue! YESSS! :tada: 

> If there's a repo already for the mozfest schedule app, I'd be happy to set up a version of the script that has all the right GitHub and Google settings and get it tested and working locally. We'd just need to decide where the script should live.

In face here *is* the repo for  the Mozfest Schedule App :bowtie: :bowtie: :bowtie: 

What do you think about "mozfest-schedule-loader" as the repo name for the Python script? It would be super rad if you could do the initial setup for "mozfest-schedule-loader" repo as I barely know anything about Python :hushed:

**Comment by ryanpitts** [comment]
Yep, working on this right now. Can you give `ryan.a.pitts@gmail.com` access to the Google spreadsheet where the data will live?

**Comment by mmmavis** [comment]
@ryanpitts thanks! I just created a spreadsheet and shared it with you. I haven't imported any data in though but hopefully that won't block your work.

**Comment by ryanpitts** [comment]
@mmmavis perfect. This script uses Oauth2 credentials to access the Google spreadsheet, so I just shared the spreadsheet with the ClientID email address I generated as well. Just wanted to give you a heads up in case you noticed a weird-looking email address on the list :)

**Comment by mmmavis** [comment]
> @mmmavis perfect. This script uses Oauth2 credentials to access the Google spreadsheet, so I just shared the spreadsheet with the ClientID email address I generated as well. Just wanted to give you a heads up in case you noticed a weird-looking email address on the list :)

Ahhhh ic! I missed this step with the npm module few days ago. Guess that's why my auth failed :grin: Learnt another thing today.  Thanks!

**Comment by ryanpitts** [comment]
About to finish adding the script to the new repo, just a couple things to document.

**Comment by mmmavis** [comment]
Thanks @ryanpitts for your help.

There's a ticket on the DevOps repo that needs your input: https://github.com/MozillaFoundation/mofo-devops/issues/193#issuecomment-146999634 mind taking a look?

**Comment by ryanpitts** [comment]
:+1:

**Comment by ryanpitts** [comment]
Loader script is here: https://github.com/mozilla/mozfest-schedule-loader. Will add a couple of issues to handle things for the new spreadsheet.

**Comment by flamingspaz** [comment]
Has a URL been decided on? I can file the issue for the SSL certificate once we have it.

**Comment by ryanpitts** [comment]
I believe we decided on schedule.mozillafestival.org

**Comment by hannahkane** [comment]
true ^

**Comment by ryanpitts** [comment]
closing this, as we decided to host the production version on S3 and use `gh-pages` -> `master` as our method of pushing changes live
