### ISSUE TITLE
Sessions not displaying day of the session

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-schedule-app#122]
Not really a bug but I remember we used to have start time displayed as `Day, Time`. eg. Saturday, 10:45 AM .  Is it possible to add it back?

@ryanpitts

**Comment by ryanpitts** [comment]
Argh, this was caused by fixing the "All Day" problem. On it.

**Comment by ryanpitts** [comment]
fixed in https://github.com/mozilla/mozfest-schedule-loader/commit/8dd17610e2996a8faf2fc2101d6fc7f85ebf6906
