### ISSUE TITLE
Link Mozfest Logo back to site

### ISSUE THREAD

**Issue by cassiemc** [mozilla/mozfest-schedule-app#13]
I think there should be a link back to the Mozfest site somewhere on the app. Does it make sense for that link to the be logo in the top left? Right now the logo currently resets the app filters, which could also be done by tapping 'all'.

http://mozilla.github.io/mozfest-schedule-app/

cc @hannahkane @xmatthewx

**Comment by xmatthewx** [comment]
I think that would be intuitive - logo links to full festival site. If the site has a good link at the top to re-enter the scheduling app, everything will be hunky-dory.

**Comment by cassiemc** [comment]
Great, let's do it!

**Comment by hannahkane** [comment]
+1
