### ISSUE TITLE
Enable search by a space, pathway or facilitators

### ISSUE THREAD

**Issue by thornet** [mozilla/mozfest-schedule-app#15]
If i search for "youthzone" in the app, it'd be great if the results returned not only any session with "youtzone" in the session description, but also in the space and pathway fields. That way, you could easily search for all sessions in a space etc. 

cc @mmmavis @ryanpitts 

Again, might be a wishlist item (#7)

**Comment by ryanpitts** [comment]
This is an easy addition, I can pick it up.

**Comment by thornet** [comment]
Hero! Thank you!
