### ISSUE TITLE
Build Spaces views

### ISSUE THREAD

**Issue by hannahkane** [mozilla/mozfest-schedule-app#18]
In the original mockups, there are views for when the user clicks on Spaces in the nav.

Spaces: https://redpen.io/bp742d484e39748ec1

They include each of the Spaces with a link to view all sessions in that Space.

(@mmmavis - I know you mentioned this in your email, but I thought there should be a ticket for it.)

**Comment by mmmavis** [comment]
thanks @hannahkane 

I separated this ticket into 2 - Pathways views ticket can be found here: https://github.com/mozilla/mozfest-schedule-app/issues/21

**Comment by mmmavis** [comment]
done and done
