### ISSUE TITLE
Build Pathways views

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-schedule-app#21]
In the original mockups, there are views for when the user clicks on Pathways in the nav.

Pathways: https://redpen.io/qs5ea730d5d8195f89

They include each of the Pathways with a link to view all sessions in that Pathway.

![mozfest 2016 mobile scheduler-04](https://cloud.githubusercontent.com/assets/11046943/10107436/f9aebdf8-6388-11e5-86f2-d06a2104c698.jpg)

![mozfest 2016 mobile scheduler-06](https://cloud.githubusercontent.com/assets/11046943/10107433/f9aca87e-6388-11e5-89ae-a8f8a3d436a4.jpg)

**Comment by mmmavis** [comment]
Just did a quick check - we currently have **80** unique pathway values entered in the source Spreadsheet... vs the ~20 Pathways listed on the [MozFest website](https://2015.mozillafestival.org/pathways). :confounded: Now I wonder if we should still build the Pathway views? Thoughts?

/cc @cassiemc @hannahkane @thornet

**Comment by thornet** [comment]
I estimate 15+ of them are going away because they were just for curation
purposes. And there's a fair bit of clean up in spelling etc. However, I do
estimate that we'll have 50 or so.

**Comment by hannahkane** [comment]
Wow. That is a lot of pathways. Seems like it will be challenging for people to parse and find the best pathways for them. Can they be grouped in any way, or is there some other organizing principle that could be used to help people find the pathways that best align with their interests?

**Comment by mmmavis** [comment]
if that's the case I think we should probably *not* show pathway description as what the first mockup suggested (we won't have copy for all of them)

**Comment by cassiemc** [comment]
Agree we should hide the description with this number of items. Maybe tap opens up the description and the listings of sessions within that pathway.

I have a concern about the website not matching the app content. That is potentially very confusing... Are we going to hide the pathways section on the website once we link up the schedule app? That is my preference, since I assume there will be ongoing updates to the pathways throughout the fest (or is that assumption misguided?)

**Comment by hannahkane** [comment]
Discussed in https://github.com/mozilla/2015.mozillafestival.org/issues/289. Seemed like @Saallen wanted to keep both pages. @Saallen - do you still feel that way? I tend to agree with Cassie. Once the schedule app is linked from the main site, the Spaces and Pathways nav items become redundant, and likely out-of-date.
