### ISSUE TITLE
Friday schedule

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-schedule-app#22]
@thornet 

Do we want to keep the Friday tab on the schedule?  I realized we didn't include any Friday options in the timeblock drowdown on the Google Spreadsheet.

**Comment by thornet** [comment]
I don't think we need Friday since it's just the science fair in the
evening that day.

Cc @saallen to confirm.

**Comment by thornet** [comment]
@mmmavis We're going to keep Friday and we'll add two sessions to it. Thanks!

**Comment by mmmavis** [comment]
@thornet cool, are there any timeblocks for Friday that I can help add to the spreadsheet (under the Main Stage tab)?
