### ISSUE TITLE
Duplicate ID used in Spreadsheet ("Seven Seconds Ago" session)

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-schedule-app#26]
The "Seven Seconds Ago" session row on the "The Global Village" tab was probably manually added and it needs to use an unique ID.  (id 615 is in use already)

/cc @thornet

**Comment by thornet** [comment]
I'll get it sorted. Thanks for catching it, Mavis!

On Fri, Oct 30, 2015 at 2:18 AM, Mavis Ou <notifications@github.com> wrote:

> The "Seven Seconds Ago" session row on the "The Global Village" tab was
> probably manually added and it needs to use an unique ID.
>
> /cc @thornet <https://github.com/thornet>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/mozfest-schedule-app/issues/26>.
>



-- 
*Michelle Thorne*
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by thornet** [comment]
Fixed.
