### ISSUE TITLE
Favourite view should only show time blocks in which there's something I've chosen

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/mozfest-schedule-app#37]
If I favourite a few sessions and go to :heart: tab, I have to scroll through all the empty time blocks to see what I've favourited. IMO, empty time blocks shouldn't show up.

**Comment by ryanpitts** [comment]
I've gone back and forth on this one, personally. On the one hand, you have to scroll past "OPEN" blocks. On the other hand, it signals to you where you still have free time to look for other sessions to attend.

Would definitely love to hear other people's opinions on this though.

**Comment by ioana-chiorean** [comment]
I agree with @secretrobotron 's proposal to show only time slots in which I have fav sessions. 
Another good User Case here are the people coming to mozfest only for a day  or an afternoon/morning. etc.

**Comment by mmmavis** [comment]
Ahhhh we need more people to vote on this!  Cuz I +1 on Ryan's thoughts!  Heh!  I would use that :heart: tab as my MozFest planner sort of thing so it's good for me to know from when to when I'm free (aka the "OPEN" blocks)

... or maybe we should add a toggle there? ha!

/cc @cassiemc :grin:

**Comment by cassiemc** [comment]
I think because it's called favorites, and not 'planner' or something like that, then like @secretrobotron I would expect to only see the things I've favorited.
