### ISSUE TITLE
find place to display sessions marked "All Saturday," "All Sunday," and "All Weekend"

### ISSUE THREAD

**Issue by ryanpitts** [mozilla/mozfest-schedule-app#40]
These currently do not have a home on the Saturday and Sunday tabs, because there's no associated scheduleblock for them. A couple options:

* Assign them to the first session scheduleblock of the day, and display the text "All day" as the "start time." So you'd have something like:

![screen shot 2015-10-30 at 1 35 25 pm](https://cloud.githubusercontent.com/assets/56477/10857396/11a59cb8-7f0b-11e5-8964-94758f12354e.png)

This would require some tweaks to the schedule loader script, but nothing difficult.

* Create a separate "All Day" scheduleblock at the top of each day's tab, just for sessions like this. This would require the addition of new blocks to the schedule template.

Any other ideas? @mmmavis @thornet @Saallen @cassiemc 

Whichever way we go here, for the sessions marked "All Weekend," I think the best solution might be to have the loader script create two versions of the session, one for Saturday and one for Sunday, so they can show up independently in each tab.

**Comment by cassiemc** [comment]
This sounds like a great solution @ryanpitts

**Comment by ryanpitts** [comment]
@cassiemc did you have a preference between the two options? Assigning them to the first scheduleblock of the day (e.g. "Saturday 10:45am" because that's when they officially start) vs. call them out in their own "All day Saturday" block on the schedule page?

**Comment by ryanpitts** [comment]
Chatted with @mmmavis -- unless anyone weighs in otherwise, we'll plan to add "All Saturday" and "All Sunday" blocks just for these sessions, at the top of their respective tabs.

**Comment by ryanpitts** [comment]
This is closed with https://github.com/mozilla/mozfest-schedule-app/commit/0774ec3418859908a95445c5b0241020a10c2332

Please reopen if we want to handle differently.

**Comment by cassiemc** [comment]
Sorry I wasn't clear. I liked the solution proposed in the screenshot with the comma + all day, but I am totally okay with this too – let's test in in situ and see how it works! Can improve it for next year if necessary. Thanks @ryanpitts
