### ISSUE TITLE
clean up whitespace around commas

### ISSUE THREAD

**Issue by ryanpitts** [mozilla/mozfest-schedule-app#42]
linebreaks in the js templates aren't playing nicely with the HTML output :(

![screen shot 2015-10-30 at 3 03 30 pm](https://cloud.githubusercontent.com/assets/56477/10859106/726ce310-7f17-11e5-9347-0e7a4895453d.png)

**Comment by mmmavis** [comment]
ahhhh guess we'll have to give up on code legibility :expressionless:

**Comment by ryanpitts** [comment]
Yeah, it's a bummer because I greatly prefer the code the way you had it written. I'm not aware of a js template filter that removes unintended whitespace though :(
