### ISSUE TITLE
Allow collapsible groupings by time

### ISSUE THREAD

**Issue by cassiemc** [mozilla/mozfest-schedule-app#52]
It might be cool to be able to 'collapse all' or 'just show the schedule'. If I'm looking to fill a particular time slot in the middle or end of the day, and I already know what I'm attending in the morning, it's a lot of scrolling past irrelevant sessions to find what I'm looking for. 

I wonder if you could add a carrot next to the day & time headers that allowed you to collapse all the sessions within that heading as a group. Then you could add a 'collapse / expand' button at the top of all the field.

**Comment by mmmavis** [comment]
this was implemented in Ryan's PR https://github.com/mozilla/mozfest-schedule-app/pull/65
