### ISSUE TITLE
Update Mozilla Learning Networks desciption

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/mozfest-schedule-app#53]
As per https://github.com/mozilla/2015.mozillafestival.org/issues/320 we updated the text on MozFest website. 
@KevZawacki should I modify the text here (http://mozilla.github.io/mozfest-schedule-app/#_spaces) too, right?

**Comment by KevZawacki** [comment]
@ioana-chiorean That would be great -- thanks!
