### ISSUE TITLE
'Moar' tweaks

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/mozfest-schedule-app#55]
5 spaces at Journalism places in schedule:
1. SAT -> Bring your web development skills to mobile  Journalism , Floor 7 - 700 
2.  SAT -> Are We Ready For Anonymity?  Journalism , Floor 7 - 703 
3. SUN -> Data journalism in the interest of an offline public  Journalism , Floor 7 - 706
4. SUN -> How to tell stories with VR, Drones and Telepresence  Journalism , Floor 7 - 700
5. SUN -> Hacking Television  Journalism , Floor 7 - 700

/sessions
157 -> (..) personal information , which is used (..)
985 -> “facilitators": "Sandra Gaudenzi , Mike Robbins",
2762 -> (..) discover relevant data , process  (..)
3173 -> "Rachel Prudden, , Met Office"
3475 - > “Carrie Anne Philbin, , Raspberry Pi Foundation”,
3477 -> "Dave Honess, , Raspberry Pi Foundation"
3585 -> "Julie Neville, , Arts Award"
3615 -> “Tom Farrow, , Mozilla",
3647 -> “ , @Lachallota"
3662 -> “ , @Lachallota"

**Comment by ryanpitts** [comment]
This PR should fix the first half of this issue, where there's an extra space around the comma: https://github.com/mozilla/mozfest-schedule-app/pull/43

**Comment by mmmavis** [comment]
r+ merging now :+1:

**Comment by mmmavis** [comment]
@ioana-chiorean I just merged the PR that Ryan submitted.  The first half of your reported issues should be fixed now! Thanks for checking the schedule data thoroughly!

I'm not sure what to do with the other half though... since that data is still being entered/edited by Space Wranglers. :grimacing:
