### ISSUE TITLE
Lunch sessions

### ISSUE THREAD

**Issue by gbaman** [mozilla/mozfest-schedule-app#66]
Would it be possible to add support for adding sessions that run over lunch? We have a few in youthZone that start and end in the lunch session.   
The only thing we can do is put them down as all Saturday or all Sunday and include the time in the description which isn't ideal.

**Comment by ryanpitts** [comment]
I think "Saturday Lunch" and "Sunday Lunch" could be added as dropdown options for this. @mmmavis ?

**Comment by mmmavis** [comment]
yea i can add those to Space tabs in the spreadsheet

**Comment by mmmavis** [comment]
done!

**Comment by mmmavis** [comment]
@gbaman i would suggest adding the exact start time in the session description :)
