### ISSUE TITLE
Info icons aren't conditional on session page

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/mozfest-schedule-app#69]
In the list by day etc, if a session doesn't has a pathway, the pathway icon smartly does not display. That's great. If you click thru to view the session, the icon appears when it shouldn't. 

<img width="864" alt="screenshot 2015-11-04 10 32 27" src="https://cloud.githubusercontent.com/assets/53411/10935657/5f17f586-82df-11e5-9bcc-74dafe163b00.png">

**Comment by ryanpitts** [comment]
Fixing template in upcoming PR

**Comment by ryanpitts** [comment]
closed in https://github.com/mozilla/mozfest-schedule-app/commit/937fd959ca5093b6bd00c7008ba6b7a3dd68e22e
