### ISSUE TITLE
Add pathway descriptions to schedule app

### ISSUE THREAD

**Issue by hannahkane** [mozilla/mozfest-schedule-app#70]
Hey @mmmavis - is it possible to port the description for each pathway from https://2015.mozillafestival.org/pathways to the schedule?

Note that not all the descriptions are done - @thornet will ask people to do this at the Thursday Space Wrangler meeting.

Originally filed here: https://github.com/mozilla/2015.mozillafestival.org/issues/344

**Comment by mmmavis** [comment]
done
