### ISSUE TITLE
FRI schedule still cut and needs scrolling

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/mozfest-schedule-app#92]
<img src="https://cloud.githubusercontent.com/assets/1391451/10998392/c2ae21ca-848c-11e5-95ac-2ab3c0333665.jpg" width="300" height="550" /> 
<img src="https://cloud.githubusercontent.com/assets/1391451/10998393/c2cc995c-848c-11e5-91f6-fffa6f79192c.jpg" width="300" height="550" /> 
![screenshot 2015-11-06 13 46 30](https://cloud.githubusercontent.com/assets/1391451/10998404/d38dd292-848c-11e5-89ba-5d8d962939d9.png)

**Comment by ryanpitts** [comment]
thanks @ioana-chiorean !

**Comment by Pomax** [comment]
fixed and landed
